export const translations = {
  en: {
    employeeListTitle: "Employee List",
    addEmployeeButton: "Add New Employee",
    firstName: "First Name",
    lastName: "Last Name",
    employmentDate: "Date of Employment",
    birthDate: "Date of Birth",
    phoneNumber: "Phone Number",
    emailAddress: "Email Address",
    department: "Department",
    position: "Position",
    next: "Next",
    previous: "Previous",
    page: "Page",
    home: "Home",
    employees: "Employees",
    description: "Click 'Employees' to manage your employees.",
    selectDepartment: 'Select Department',
    analytics: 'Analytics',
    tech: 'Tech',
    position: 'Position',
    selectPosition: 'Select Position',
    junior: 'Junior',
    medior: 'Medior',
    senior: 'Senior',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete Employee',
    employee: 'Employee: ',
    of: 'of',
    confirm: 'Are you sure you want to delete this employee?',
    invalidPhoneNumber: "Please enter a valid phone number. Only '+' and digits are allowed.",
    invalidName: "Please enter a valid name. Only letters and spaces are allowed."
  },
  tr: {
    employeeListTitle: "Çalışan Listesi",
    addEmployeeButton: "Yeni Çalışan Ekle",
    firstName: "Ad",
    lastName: "Soyad",
    employmentDate: "İşe Başlama Tarihi",
    birthDate: "Doğum Tarihi",
    phoneNumber: "Telefon Numarası",
    emailAddress: "E-posta Adresi",
    department: "Departman",
    position: "Pozisyon",
    next: "Sonraki",
    previous: "Önceki",
    page: "Sayfa",
    home: "Ana Sayfa",
    employees: "Çalışanlar",
    description: "Çalışanları görüntülemek ve ekleme/çıkarma yapmak için 'Çalışanlar' sekmesine gidiniz.",
    selectDepartment: 'Departman Seç',
    analytics: 'Analytics',
    tech: 'Tech',
    position: 'Pozisyon',
    selectPosition: 'Pozisyon Seç',
    junior: 'Junior',
    medior: 'Medior',
    senior: 'Senior',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Çalışanı Sil',
    employee: 'Çalışan: ',
    of: '-',
    confirm: 'Bu çalışanı silmek istediğinize emin misiniz?',
    invalidPhoneNumber: "Lütfen geçerli bir telefon numarası girin. Sadece '+' ve rakamlara izin verilir.",
    invalidName: "Lütfen geçerli bir isim girin. Sadece harfler ve boşluklara izin verilir."
  },
};
